<div class="modal-dialog">
	<div class="modal-content form-container">
		<div class="modal-header">
			<button type="button" class="close" data-dismiss="modal">
				<span aria-hidden="true">&times;</span><span class="sr-only">Close</span>
			</button>
			<h4 class="modal-title">Import Pictures</h4>
		</div>
		<div class="modal-body">
			<form method="post" action="/admin/manage/importphoto" enctype="multipart/form-data" id="importPhotoForm">
				<input type="hidden" name="subcategory_id" value="<?php echo $this->subcategory_id; ?>" />
				<div class="form-group">
                    <label for="pictures">Pictures</label>
                    <input type="file" name="pictures[]" accept="audio/*|video/*|image/*" multiple="">
                    <!-- <input type="file" name="pictures[]" accept="image/*"/ multiple=""> -->
                </div>
            </form>
            
            <div class="progress hide" id="importPhotoProgress">
				<div class="progress progress-striped active">
                    <div class="progress-bar progress-bar-primary" role="progressbar" aria-valuenow="0" aria-valuemin="0" aria-valuemax="100" style="width: 0%">
                        <span class="sr-only">0%</span>
                    </div>
                </div>
			</div>
		</div>
		<div class="modal-footer">
			<button type="button" class="btn btn-default closeModalBtn" data-dismiss="modal">Cancel</button>
			<button type="submit" class="btn btn-primary" form="importPhotoForm" id="importPhotoSubmit">Submit</button>
		</div>
	</div>
</div>
