<div class="modal-dialog">
	<div class="modal-content form-container">
		<div class="modal-header">
			<button type="button" class="close" data-dismiss="modal">
				<span aria-hidden="true">&times;</span><span class="sr-only">Close</span>
			</button>
			<h4 class="modal-title">Prefix Name</h4>
		</div>
		<div class="modal-body">
			<div class="form-group">
                <label for="prefix">Prefix</label>
                <input type="text" class="form-control" name="prefix" id="prefix" placeholder="Enter prefix" >
            </div>
            <div class="form-group">
                <div class="radio">
                    <label>
                        <input type="radio" name="prefixOption" id="prefixOption1" value="0">
                        Add to contents's name
                    </label>
                </div>
                <div class="radio">
                    <label>
                        <input type="radio" name="prefixOption" id="prefixOption2" value="1" checked="TRUE">
                        Remove from contents's name
                    </label>
                </div>
            </div>
		</div>
		<div class="modal-footer">
			<button type="button" class="btn btn-default" data-dismiss="modal">
				Cancel
			</button>
			<button type="button" onclick="fixNameItem()" class="btn btn-primary">
				Fix
			</button>
		</div>
	</div>
</div>
