<h1>CSS3 Checkbox Styles</h1>

<!-- Slide ONE -->
<div class="slideOne">	
	<input class="simple" type="checkbox" value="None" id="slideOne" name="check" />
	<label for="slideOne"></label>
</div>

<!-- Slide TWO -->
<div class="slideTwo">	
	<input class="simple" type="checkbox" value="None" id="slideTwo" name="check" />
	<label for="slideTwo"></label>
</div>

<!-- Slide THREE -->
<div class="slideThree">	
	<input class="simple" type="checkbox" value="None" id="slideThree" name="check" />
	<label for="slideThree"></label>
</div>

<!-- Rounded ONE -->
<div class="roundedOne">
	<input class="simple" type="checkbox" value="None" id="roundedOne" name="check" />
	<label for="roundedOne"></label>
</div>

<!-- Rounded TWO -->
<div class="roundedTwo">
	<input class="simple" type="checkbox" value="None" id="roundedTwo" name="check" />
	<label for="roundedTwo"></label>
</div>

<!-- Squared ONE -->
<div class="squaredOne">
	<input class="simple" type="checkbox" value="None" id="squaredOne" name="check" />
	<label for="squaredOne"></label>
</div>

<!-- Squared TWO -->
<div class="squaredTwo">
	<input class="simple" type="checkbox" value="None" id="squaredTwo" name="check" />
	<label for="squaredTwo"></label>
</div>

<!-- Squared THREE -->
<div class="squaredThree">
	<input class="simple" type="checkbox" value="None" id="squaredThree" name="check" />
	<label for="squaredThree"></label>
</div>

<!-- Squared FOUR -->
<div class="squaredFour">
	<input class="simple" type="checkbox" value="None" id="squaredFour" name="check" />
	<label for="squaredFour"></label>
</div>

<style>
input[type=checkbox] {
	visibility: hidden;
}
/* SQUARED FOUR */
.squaredFour {
	width: 20px;	
	margin: 20px auto;
	position: relative;
}

.squaredFour label {
	cursor: pointer;
	position: absolute;
	width: 20px;
	height: 20px;
	top: 0;
	border-radius: 4px;

	-webkit-box-shadow: inset 0px 1px 1px white, 0px 1px 3px rgba(0,0,0,0.5);
	-moz-box-shadow: inset 0px 1px 1px white, 0px 1px 3px rgba(0,0,0,0.5);
	box-shadow: inset 0px 1px 1px white, 0px 1px 3px rgba(0,0,0,0.5);
	background: #fcfff4;

	background: -webkit-linear-gradient(top, #fcfff4 0%, #dfe5d7 40%, #b3bead 100%);
	background: -moz-linear-gradient(top, #fcfff4 0%, #dfe5d7 40%, #b3bead 100%);
	background: -o-linear-gradient(top, #fcfff4 0%, #dfe5d7 40%, #b3bead 100%);
	background: -ms-linear-gradient(top, #fcfff4 0%, #dfe5d7 40%, #b3bead 100%);
	background: linear-gradient(top, #fcfff4 0%, #dfe5d7 40%, #b3bead 100%);
	filter: progid:DXImageTransform.Microsoft.gradient( startColorstr='#fcfff4', endColorstr='#b3bead',GradientType=0 );
}

.squaredFour label:after {
	-ms-filter: "progid:DXImageTransform.Microsoft.Alpha(Opacity=0)";
	filter: alpha(opacity=0);
	opacity: 0;
	content: '';
	position: absolute;
	width: 12px;
	height: 8px;
	background: transparent;
	top: 4px;
	left: 4px;
	border: 3px solid #333;
	border-top: none;
	border-right: none;

	-webkit-transform: rotate(-45deg);
	-moz-transform: rotate(-45deg);
	-o-transform: rotate(-45deg);
	-ms-transform: rotate(-45deg);
	transform: rotate(-45deg);
}

.squaredFour label:hover::after {
	-ms-filter: "progid:DXImageTransform.Microsoft.Alpha(Opacity=30)";
	filter: alpha(opacity=30);
	opacity: 0.5;
}

.squaredFour input[type=checkbox]:checked + label:after {
	-ms-filter: "progid:DXImageTransform.Microsoft.Alpha(Opacity=100)";
	filter: alpha(opacity=100);
	opacity: 1;
}

</style>