<a href="<?php echo $this->fbLoginUrl."&testspafs=asrvgsdrasv"; ?>" class="btn btn-primary">FB Login</a>

<!--<script>-->
<!--$(document).ready(function() {-->
<!--	$.ajaxSetup({ cache: true });-->
<!--	$.getScript('//connect.facebook.net/en_UK/all.js', function(){-->
<!--		FB.init({-->
<!--			appId: '808852962491530',-->
<!--		});-->
<!---->
<!--		$('#loginbutton,#feedbutton').removeAttr('disabled');-->
<!---->
<!--		FB.getLoginStatus(function(response) {-->
<!--			if (response.status === 'connected') {-->
<!--				console.log('Logged in.');-->
<!--			}-->
<!--			else {-->
<!--				FB.login();-->
<!--			}-->
<!--		});-->
<!--	});-->
<!--});-->
<!---->
<!---->
<!--function getPhotos(){-->
<!--	FB.api("/100001337796176/albums",function(data){-->
<!--		console.log(data);-->
<!--	});-->
<!--}-->
<!--</script>-->