<!--<script type="text/javascript" src="/assets/plugins/jwplayer/jwplayer.html5.js"></script>-->
<script type="text/javascript" src="/assets/plugins/jwplayer/jwplayer.js"></script>

<div id='playerWENhJpCIgUwk'></div>
<script type='text/javascript'>
    jwplayer.key="QkxtcYGigdqUvO4e5o5a4WYWIVLBF2Zaw/pcxg==";
    jwplayer('playerWENhJpCIgUwk').setup({
        file: '<?php echo $this->streamUrl; ?>',
        title: 'Test streaming video'
//        width: '100%',
    });
</script>

<img src="/store/2014/12/2661090_Windows-10-Invite.jpg">